import { Template } from "@/types";

export const templates: Template[] = [
  {
    id: "1",
    name: "Acuerdo de Confidencialidad (NDA)",
    slug: "nda",
    description:
      "Protege información confidencial entre partes comerciales o laborales",
    icon: "Shield",
    category: "Contratos y Acuerdos",
    outputType: "Borrador",
    variables: [
      {
        name: "parte_reveladora",
        label: "Parte Reveladora (quien comparte la información)",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "parte_receptora",
        label: "Parte Receptora (quien recibe la información)",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "tipo_informacion",
        label: "Tipo de Información Confidencial",
        type: "textarea",
        required: true,
        placeholder:
          "Ej: Datos financieros, estrategias comerciales, código fuente...",
      },
      {
        name: "duracion",
        label: "Duración del Acuerdo",
        type: "select",
        required: true,
        options: ["1 año", "2 años", "3 años", "5 años", "Indefinido"],
      },
      {
        name: "jurisdiccion",
        label: "Jurisdicción Aplicable",
        type: "select",
        required: true,
        options: ["Colombia", "México", "Argentina", "Chile", "Perú", "España"],
      },
    ],
    system_prompt: "Genera un Acuerdo de Confidencialidad (NDA) bilateral completo.",
  },
  {
    id: "2",
    name: "Contrato",
    slug: "contrato",
    description:
      "Genera contratos de prestación de servicios, arrendamiento, laboral, comercial y más",
    icon: "FileText",
    category: "Contratos y Acuerdos",
    outputType: "Borrador",
    variables: [
      {
        name: "tipo_contrato",
        label: "Tipo de Contrato",
        type: "select",
        required: true,
        options: [
          "Prestación de Servicios",
          "Arrendamiento",
          "Laboral a Término Fijo",
          "Laboral a Término Indefinido",
          "Compraventa",
          "Distribución / Comercial",
          "Mandato / Agencia",
          "Consultoría",
          "Otro",
        ],
      },
      {
        name: "parte_a",
        label: "Primera Parte",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "parte_b",
        label: "Segunda Parte",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "objeto",
        label: "Objeto del Contrato",
        type: "textarea",
        required: true,
        placeholder: "Describa el propósito y alcance del contrato...",
      },
      {
        name: "valor",
        label: "Valor / Contraprestación",
        type: "text",
        required: true,
        placeholder: "Ej: $5,000,000 COP mensuales",
      },
      {
        name: "duracion",
        label: "Duración del Contrato",
        type: "text",
        required: true,
        placeholder: "Ej: 6 meses, 1 año, indefinido",
      },
      {
        name: "jurisdiccion",
        label: "Jurisdicción",
        type: "select",
        required: true,
        options: ["Colombia", "México", "Argentina", "Chile", "Perú", "España"],
      },
    ],
    system_prompt:
      "Genera un contrato profesional completo según el tipo seleccionado. Incluye cláusulas estándar de obligaciones, terminación, penalidades, confidencialidad, resolución de conflictos y disposiciones generales.",
  },
  {
    id: "3",
    name: "Carta / Correo Electrónico",
    slug: "carta_correo",
    description:
      "Redacta cartas formales, correos profesionales, notificaciones y comunicaciones oficiales",
    icon: "FileX",
    category: "Comunicaciones Formales",
    outputType: "Borrador",
    variables: [
      {
        name: "tipo_comunicacion",
        label: "Tipo de Comunicación",
        type: "select",
        required: true,
        options: [
          "Carta de Terminación de Contrato",
          "Carta de Renuncia",
          "Notificación Legal",
          "Carta de Cobro / Requerimiento",
          "Carta de Referencia Laboral",
          "Correo Profesional Formal",
          "Comunicado Interno",
          "Carta de Intención",
          "Otro",
        ],
      },
      {
        name: "remitente",
        label: "Remitente",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "destinatario",
        label: "Destinatario",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "asunto",
        label: "Asunto / Propósito",
        type: "textarea",
        required: true,
        placeholder: "Describa el propósito de la comunicación y los puntos clave a incluir...",
      },
      {
        name: "tono",
        label: "Tono",
        type: "select",
        required: true,
        options: ["Formal", "Semiformal", "Firme / Asertivo", "Cordial"],
      },
    ],
    system_prompt:
      "Genera una comunicación profesional según el tipo seleccionado. Si es carta, usa formato de carta formal con fecha, encabezado, cuerpo y cierre. Si es correo electrónico, usa formato de email profesional con asunto, saludo, cuerpo y despedida.",
  },
  {
    id: "4",
    name: "Acta de Reunión",
    slug: "acta_reunion",
    description: "Documenta los temas tratados y acuerdos de una reunión",
    icon: "Users",
    category: "Comunicaciones Formales",
    outputType: "Acta",
    variables: [
      {
        name: "titulo_reunion",
        label: "Título de la Reunión",
        type: "text",
        required: true,
        placeholder: "Ej: Reunión de Junta Directiva Q4 2024",
      },
      {
        name: "fecha_reunion",
        label: "Fecha de la Reunión",
        type: "date",
        required: true,
      },
      {
        name: "lugar",
        label: "Lugar de la Reunión",
        type: "text",
        required: true,
        placeholder: "Ej: Sala de juntas principal / Virtual (Zoom)",
      },
      {
        name: "asistentes",
        label: "Asistentes",
        type: "textarea",
        required: true,
        placeholder: "Liste los asistentes, uno por línea",
      },
      {
        name: "temas_tratados",
        label: "Temas Tratados",
        type: "textarea",
        required: true,
        placeholder: "Liste los temas discutidos...",
      },
      {
        name: "acuerdos",
        label: "Acuerdos y Compromisos",
        type: "textarea",
        required: true,
        placeholder: "Liste los acuerdos alcanzados...",
      },
    ],
    system_prompt: "Genera un Acta de Reunión formal y estructurada.",
  },
  {
    id: "5",
    name: "Política Interna",
    slug: "politica_interna",
    description: "Define lineamientos y reglas para la organización",
    icon: "BookOpen",
    category: "Políticas y Normativas",
    outputType: "Política",
    variables: [
      {
        name: "empresa",
        label: "Nombre de la Empresa",
        type: "text",
        required: true,
        placeholder: "Razón social de la empresa",
      },
      {
        name: "tipo_politica",
        label: "Tipo de Política",
        type: "select",
        required: true,
        options: [
          "Política de Protección de Datos",
          "Política de Trabajo Remoto",
          "Política de Uso de Equipos",
          "Política de Vacaciones",
          "Política de Gastos",
          "Código de Ética",
        ],
      },
      {
        name: "alcance",
        label: "Alcance (a quién aplica)",
        type: "text",
        required: true,
        placeholder: "Ej: Todos los empleados, Solo área comercial",
      },
      {
        name: "puntos_clave",
        label: "Puntos Clave a Incluir",
        type: "textarea",
        required: true,
        placeholder: "Liste los aspectos más importantes que debe cubrir...",
      },
      {
        name: "consecuencias",
        label: "Consecuencias por Incumplimiento",
        type: "textarea",
        required: false,
        placeholder: "Opcional: Sanciones o consecuencias",
      },
    ],
    system_prompt: "Genera una Política Interna corporativa completa y profesional.",
  },
  {
    id: "6",
    name: "Reporte de Desempeño",
    slug: "performance_report",
    description:
      "Genera reportes de evaluación de desempeño, feedback estructurado y planes de mejora",
    icon: "FileText",
    category: "Reportes y Evaluaciones",
    outputType: "Reporte",
    variables: [
      {
        name: "tipo_reporte",
        label: "Tipo de Reporte",
        type: "select",
        required: true,
        options: [
          "Evaluación de Desempeño Anual",
          "Evaluación Trimestral",
          "Plan de Mejora (PIP)",
          "Feedback 360°",
          "Reporte de Período de Prueba",
          "Resumen de 1:1s",
        ],
      },
      {
        name: "evaluado",
        label: "Nombre del Evaluado",
        type: "text",
        required: true,
        placeholder: "Nombre completo del empleado",
      },
      {
        name: "cargo",
        label: "Cargo / Posición",
        type: "text",
        required: true,
        placeholder: "Ej: Desarrollador Senior, Gerente Comercial",
      },
      {
        name: "periodo",
        label: "Período Evaluado",
        type: "text",
        required: true,
        placeholder: "Ej: Enero - Diciembre 2024, Q3 2024",
      },
      {
        name: "logros",
        label: "Logros y Fortalezas",
        type: "textarea",
        required: true,
        placeholder: "Describa los principales logros, metas cumplidas y fortalezas observadas...",
      },
      {
        name: "areas_mejora",
        label: "Áreas de Mejora",
        type: "textarea",
        required: true,
        placeholder: "Describa las oportunidades de desarrollo y puntos a mejorar...",
      },
      {
        name: "objetivos",
        label: "Objetivos para el Próximo Período",
        type: "textarea",
        required: false,
        placeholder: "Opcional: Metas y KPIs para el siguiente período",
      },
    ],
    system_prompt:
      "Genera un reporte de desempeño profesional y estructurado según el tipo seleccionado. Usa un tono objetivo, constructivo y orientado al desarrollo. Incluye secciones claras, métricas cuando sea posible y recomendaciones accionables.",
  },
];

export function getTemplateBySlug(slug: string): Template | undefined {
  return templates.find((t) => t.slug === slug);
}
