import { Template } from "@/types";

const baseTemplates: Template[] = [
  {
    id: "1",
    name: "Acuerdo de Confidencialidad (NDA)",
    slug: "nda",
    description:
      "Protege información confidencial entre partes comerciales o laborales",
    icon: "Shield",
    category: "Contratos y Acuerdos",
    outputType: "Borrador",
    variables: [
      {
        name: "parte_reveladora",
        label: "Parte Reveladora (quien comparte la información)",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "parte_receptora",
        label: "Parte Receptora (quien recibe la información)",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "tipo_informacion",
        label: "Tipo de Información Confidencial",
        type: "textarea",
        required: true,
        placeholder:
          "Ej: Datos financieros, estrategias comerciales, código fuente...",
      },
      {
        name: "duracion",
        label: "Duración del Acuerdo",
        type: "select",
        required: true,
        options: ["1 año", "2 años", "3 años", "5 años", "Indefinido"],
      },
      {
        name: "jurisdiccion",
        label: "Jurisdicción Aplicable",
        type: "select",
        required: true,
        options: ["Colombia", "México", "Argentina", "Chile", "Perú", "España"],
      },
    ],
    system_prompt: "Genera un Acuerdo de Confidencialidad (NDA) bilateral completo.",
  },
  {
    id: "2",
    name: "Contrato",
    slug: "contrato",
    description:
      "Genera contratos de prestación de servicios, arrendamiento, laboral, comercial y más",
    icon: "FileText",
    category: "Contratos y Acuerdos",
    outputType: "Borrador",
    variables: [
      {
        name: "tipo_contrato",
        label: "Tipo de Contrato",
        type: "select",
        required: true,
        options: [
          "Prestación de Servicios",
          "Arrendamiento",
          "Laboral a Término Fijo",
          "Laboral a Término Indefinido",
          "Compraventa",
          "Distribución / Comercial",
          "Mandato / Agencia",
          "Consultoría",
          "Otro",
        ],
      },
      {
        name: "parte_a",
        label: "Primera Parte",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "parte_b",
        label: "Segunda Parte",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "objeto",
        label: "Objeto del Contrato",
        type: "textarea",
        required: true,
        placeholder: "Describa el propósito y alcance del contrato...",
      },
      {
        name: "valor",
        label: "Valor / Contraprestación",
        type: "text",
        required: true,
        placeholder: "Ej: $5,000,000 COP mensuales",
      },
      {
        name: "duracion",
        label: "Duración del Contrato",
        type: "text",
        required: true,
        placeholder: "Ej: 6 meses, 1 año, indefinido",
      },
      {
        name: "jurisdiccion",
        label: "Jurisdicción",
        type: "select",
        required: true,
        options: ["Colombia", "México", "Argentina", "Chile", "Perú", "España"],
      },
    ],
    system_prompt:
      "Genera un contrato profesional completo según el tipo seleccionado. Incluye cláusulas estándar de obligaciones, terminación, penalidades, confidencialidad, resolución de conflictos y disposiciones generales.",
  },
  {
    id: "3",
    name: "Carta / Correo Electrónico",
    slug: "carta_correo",
    description:
      "Redacta cartas formales, correos profesionales, notificaciones y comunicaciones oficiales",
    icon: "FileX",
    category: "Comunicaciones Formales",
    outputType: "Borrador",
    variables: [
      {
        name: "tipo_comunicacion",
        label: "Tipo de Comunicación",
        type: "select",
        required: true,
        options: [
          "Carta de Terminación de Contrato",
          "Carta de Renuncia",
          "Notificación Legal",
          "Carta de Cobro / Requerimiento",
          "Carta de Referencia Laboral",
          "Correo Profesional Formal",
          "Comunicado Interno",
          "Carta de Intención",
          "Otro",
        ],
      },
      {
        name: "remitente",
        label: "Remitente",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "destinatario",
        label: "Destinatario",
        type: "text",
        required: true,
        placeholder: "Nombre completo o razón social",
      },
      {
        name: "asunto",
        label: "Asunto / Propósito",
        type: "textarea",
        required: true,
        placeholder: "Describa el propósito de la comunicación y los puntos clave a incluir...",
      },
      {
        name: "tono",
        label: "Tono",
        type: "select",
        required: true,
        options: ["Formal", "Semiformal", "Firme / Asertivo", "Cordial"],
      },
    ],
    system_prompt:
      "Genera una comunicación profesional según el tipo seleccionado. Si es carta, usa formato de carta formal con fecha, encabezado, cuerpo y cierre. Si es correo electrónico, usa formato de email profesional con asunto, saludo, cuerpo y despedida.",
  },
  {
    id: "4",
    name: "Acta de Reunión",
    slug: "acta_reunion",
    description: "Documenta los temas tratados y acuerdos de una reunión",
    icon: "Users",
    category: "Comunicaciones Formales",
    outputType: "Acta",
    variables: [
      {
        name: "titulo_reunion",
        label: "Título de la Reunión",
        type: "text",
        required: true,
        placeholder: "Ej: Reunión de Junta Directiva Q4 2024",
      },
      {
        name: "fecha_reunion",
        label: "Fecha de la Reunión",
        type: "date",
        required: true,
      },
      {
        name: "lugar",
        label: "Lugar de la Reunión",
        type: "text",
        required: true,
        placeholder: "Ej: Sala de juntas principal / Virtual (Zoom)",
      },
      {
        name: "asistentes",
        label: "Asistentes",
        type: "textarea",
        required: true,
        placeholder: "Liste los asistentes, uno por línea",
      },
      {
        name: "temas_tratados",
        label: "Temas Tratados",
        type: "textarea",
        required: true,
        placeholder: "Liste los temas discutidos...",
      },
      {
        name: "acuerdos",
        label: "Acuerdos y Compromisos",
        type: "textarea",
        required: true,
        placeholder: "Liste los acuerdos alcanzados...",
      },
    ],
    system_prompt: "Genera un Acta de Reunión formal y estructurada.",
  },
  {
    id: "5",
    name: "Política Interna",
    slug: "politica_interna",
    description: "Define lineamientos y reglas para la organización",
    icon: "BookOpen",
    category: "Políticas y Normativas",
    outputType: "Política",
    variables: [
      {
        name: "empresa",
        label: "Nombre de la Empresa",
        type: "text",
        required: true,
        placeholder: "Razón social de la empresa",
      },
      {
        name: "tipo_politica",
        label: "Tipo de Política",
        type: "select",
        required: true,
        options: [
          "Política de Protección de Datos",
          "Política de Trabajo Remoto",
          "Política de Uso de Equipos",
          "Política de Vacaciones",
          "Política de Gastos",
          "Código de Ética",
        ],
      },
      {
        name: "alcance",
        label: "Alcance (a quién aplica)",
        type: "text",
        required: true,
        placeholder: "Ej: Todos los empleados, Solo área comercial",
      },
      {
        name: "puntos_clave",
        label: "Puntos Clave a Incluir",
        type: "textarea",
        required: true,
        placeholder: "Liste los aspectos más importantes que debe cubrir...",
      },
      {
        name: "consecuencias",
        label: "Consecuencias por Incumplimiento",
        type: "textarea",
        required: false,
        placeholder: "Opcional: Sanciones o consecuencias",
      },
    ],
    system_prompt: "Genera una Política Interna corporativa completa y profesional.",
  },
  {
    id: "6",
    name: "Reporte de Desempeño",
    slug: "performance_report",
    description:
      "Genera reportes de evaluación de desempeño, feedback estructurado y planes de mejora",
    icon: "FileText",
    category: "Reportes y Evaluaciones",
    outputType: "Reporte",
    variables: [
      {
        name: "tipo_reporte",
        label: "Tipo de Reporte",
        type: "select",
        required: true,
        options: [
          "Evaluación de Desempeño Anual",
          "Evaluación Trimestral",
          "Plan de Mejora (PIP)",
          "Feedback 360°",
          "Reporte de Período de Prueba",
          "Resumen de 1:1s",
        ],
      },
      {
        name: "evaluado",
        label: "Nombre del Evaluado",
        type: "text",
        required: true,
        placeholder: "Nombre completo del empleado",
      },
      {
        name: "cargo",
        label: "Cargo / Posición",
        type: "text",
        required: true,
        placeholder: "Ej: Desarrollador Senior, Gerente Comercial",
      },
      {
        name: "periodo",
        label: "Período Evaluado",
        type: "text",
        required: true,
        placeholder: "Ej: Enero - Diciembre 2024, Q3 2024",
      },
      {
        name: "logros",
        label: "Logros y Fortalezas",
        type: "textarea",
        required: true,
        placeholder: "Describa los principales logros, metas cumplidas y fortalezas observadas...",
      },
      {
        name: "areas_mejora",
        label: "Áreas de Mejora",
        type: "textarea",
        required: true,
        placeholder: "Describa las oportunidades de desarrollo y puntos a mejorar...",
      },
      {
        name: "objetivos",
        label: "Objetivos para el Próximo Período",
        type: "textarea",
        required: false,
        placeholder: "Opcional: Metas y KPIs para el siguiente período",
      },
    ],
    system_prompt:
      "Genera un reporte de desempeño profesional y estructurado según el tipo seleccionado. Usa un tono objetivo, constructivo y orientado al desarrollo. Incluye secciones claras, métricas cuando sea posible y recomendaciones accionables.",
  },
];

// ===========================================
// Immigration Templates
// ===========================================

const immigrationTemplates: Template[] = [
  {
    id: "7",
    name: "Cover Letter Consular",
    slug: "cover-letter-consular",
    description:
      "Professional consular cover letter for US visa applications and embassy submissions",
    icon: "Globe",
    category: "Inmigración",
    outputType: "Carta",
    variables: [
      {
        name: "applicant_name",
        label: "Applicant Full Name",
        type: "text",
        required: true,
        placeholder: "Full legal name of the applicant",
      },
      {
        name: "visa_category",
        label: "Visa Category",
        type: "text",
        required: true,
        placeholder: "E.g. H-1B, L-1A, O-1, EB-2 NIW",
      },
      {
        name: "consulate_city",
        label: "Consulate City",
        type: "text",
        required: true,
        placeholder: "E.g. Bogotá, Mexico City, São Paulo",
      },
      {
        name: "consulate_country",
        label: "Consulate Country",
        type: "text",
        required: true,
        placeholder: "E.g. Colombia, Mexico, Brazil",
      },
      {
        name: "officer_title",
        label: "Consular Officer Title",
        type: "text",
        required: false,
        placeholder: "E.g. Consular Officer, Visa Section Chief",
      },
      {
        name: "petition_basis",
        label: "Petition Basis",
        type: "textarea",
        required: true,
        placeholder: "Describe the legal basis for this visa petition...",
      },
      {
        name: "key_facts",
        label: "Key Facts",
        type: "textarea",
        required: true,
        placeholder: "Key facts about the applicant relevant to the petition...",
      },
      {
        name: "supporting_evidence",
        label: "Supporting Evidence Summary",
        type: "textarea",
        required: true,
        placeholder: "List the supporting documents and their significance...",
      },
      {
        name: "attorney_name",
        label: "Attorney Name",
        type: "text",
        required: true,
        placeholder: "Full name of the filing attorney",
      },
      {
        name: "law_firm_name",
        label: "Law Firm Name",
        type: "text",
        required: true,
        placeholder: "Name of the law firm",
      },
    ],
    system_prompt:
      "You are an expert US immigration attorney. Generate the document in English. Generate a professional consular cover letter in the format standard for US visa applications. Use formal legal language. Structure: opening identifying the applicant, visa category and petition basis, summary of supporting evidence, closing request.",
    steps: [
      {
        title: "Client Info",
        fields: ["applicant_name", "visa_category"],
      },
      {
        title: "Consulate Details",
        fields: ["consulate_city", "consulate_country", "officer_title"],
      },
      {
        title: "Petition Basis",
        fields: ["petition_basis", "key_facts", "supporting_evidence"],
      },
      {
        title: "Firm Info",
        fields: ["attorney_name", "law_firm_name"],
      },
    ],
  },
  {
    id: "8",
    name: "Cover Letter USCIS",
    slug: "cover-letter-uscis",
    description:
      "Professional USCIS cover letter for petition and application filings",
    icon: "FileCheck",
    category: "Inmigración",
    outputType: "Carta",
    variables: [
      {
        name: "applicant_name",
        label: "Applicant Full Name",
        type: "text",
        required: true,
        placeholder: "Full legal name of the applicant",
      },
      {
        name: "a_number",
        label: "A-Number (Alien Registration Number)",
        type: "text",
        required: false,
        placeholder: "E.g. A-123 456 789",
      },
      {
        name: "form_type",
        label: "Form Type",
        type: "text",
        required: true,
        placeholder: "E.g. I-130, I-485, I-765, I-140",
      },
      {
        name: "receipt_number",
        label: "Receipt Number",
        type: "text",
        required: false,
        placeholder: "E.g. EAC-24-123-45678",
      },
      {
        name: "filing_basis",
        label: "Filing Basis",
        type: "textarea",
        required: true,
        placeholder: "Describe the legal basis for this filing...",
      },
      {
        name: "key_facts",
        label: "Key Facts",
        type: "textarea",
        required: true,
        placeholder: "Key facts supporting this filing...",
      },
      {
        name: "supporting_documents",
        label: "Supporting Documents",
        type: "textarea",
        required: true,
        placeholder: "List all supporting documents included in this submission...",
      },
      {
        name: "attorney_name",
        label: "Attorney Name",
        type: "text",
        required: true,
        placeholder: "Full name of the filing attorney",
      },
    ],
    system_prompt:
      "You are an expert US immigration attorney. Generate the document in English. Generate a professional USCIS cover letter for a petition or application filing. Include reference to the form type and receipt number if provided. Summarize the filing basis and enumerate the supporting documents.",
    steps: [
      {
        title: "Client Info",
        fields: ["applicant_name", "a_number"],
      },
      {
        title: "Filing Details",
        fields: ["form_type", "receipt_number", "filing_basis"],
      },
      {
        title: "Supporting Documents",
        fields: ["key_facts", "supporting_documents", "attorney_name"],
      },
    ],
  },
  {
    id: "9",
    name: "Personal Declaration",
    slug: "personal-declaration",
    description:
      "First-person sworn personal declaration for immigration proceedings",
    icon: "UserCheck",
    category: "Inmigración",
    outputType: "Declaración",
    variables: [
      {
        name: "declarant_name",
        label: "Declarant Full Name",
        type: "text",
        required: true,
        placeholder: "Full legal name of the person making the declaration",
      },
      {
        name: "country_of_birth",
        label: "Country of Birth",
        type: "text",
        required: true,
        placeholder: "E.g. Mexico, Colombia, Brazil",
      },
      {
        name: "date_of_entry",
        label: "Date of Entry to the US",
        type: "date",
        required: true,
      },
      {
        name: "port_of_entry",
        label: "Port of Entry",
        type: "text",
        required: true,
        placeholder: "E.g. JFK Airport, New York; Laredo, Texas",
      },
      {
        name: "current_immigration_status",
        label: "Current Immigration Status",
        type: "text",
        required: true,
        placeholder: "E.g. Pending asylum, DACA recipient, H-1B holder",
      },
      {
        name: "chronological_facts",
        label: "Chronological Facts",
        type: "textarea",
        required: true,
        placeholder: "Tell the story chronologically — entry, key events, current situation...",
      },
      {
        name: "relief_sought",
        label: "Relief Sought",
        type: "textarea",
        required: true,
        placeholder: "What relief or benefit is the declarant seeking and why...",
      },
      {
        name: "declaration_date",
        label: "Declaration Date",
        type: "date",
        required: true,
      },
    ],
    system_prompt:
      "You are an expert US immigration attorney. Generate the document in English. Generate a first-person sworn personal declaration for immigration proceedings. Use \"I\" throughout. Include a formal declaration header (\"I, [name], declare under penalty of perjury under the laws of the United States of America that the following is true and correct:\"). Tell the story chronologically. End with a formal signature block.",
    steps: [
      {
        title: "Identity",
        fields: ["declarant_name", "country_of_birth"],
      },
      {
        title: "Entry & Status",
        fields: ["date_of_entry", "port_of_entry", "current_immigration_status"],
      },
      {
        title: "Facts & Relief",
        fields: ["chronological_facts", "relief_sought"],
      },
      {
        title: "Finalize",
        fields: ["declaration_date"],
      },
    ],
  },
  {
    id: "10",
    name: "Legal Argument Brief",
    slug: "legal-argument",
    description:
      "Formal legal argument brief section for immigration cases",
    icon: "Scale",
    category: "Inmigración",
    outputType: "Brief",
    variables: [
      {
        name: "case_name",
        label: "Case Name",
        type: "text",
        required: true,
        placeholder: "E.g. Matter of Rodriguez, File No. A-123456789",
      },
      {
        name: "issue_presented",
        label: "Issue Presented",
        type: "textarea",
        required: true,
        placeholder: "State the precise legal question to be resolved...",
      },
      {
        name: "applicable_statute",
        label: "Applicable Statute / Regulation",
        type: "text",
        required: true,
        placeholder: "E.g. INA § 101(a)(15)(H)(i)(b), 8 C.F.R. § 214.2(h)",
      },
      {
        name: "legal_standard",
        label: "Legal Standard",
        type: "textarea",
        required: true,
        placeholder: "State the applicable legal standard and cite relevant case law...",
      },
      {
        name: "facts",
        label: "Statement of Facts",
        type: "textarea",
        required: true,
        placeholder: "Summarize the relevant facts of the case...",
      },
      {
        name: "argument",
        label: "Argument",
        type: "textarea",
        required: true,
        placeholder: "Apply law to facts — make the argument...",
      },
      {
        name: "conclusion",
        label: "Conclusion",
        type: "textarea",
        required: true,
        placeholder: "State the relief requested and why it should be granted...",
      },
      {
        name: "attorney_name",
        label: "Attorney Name",
        type: "text",
        required: true,
        placeholder: "Full name of the filing attorney",
      },
    ],
    system_prompt:
      "You are an expert US immigration attorney. Generate the document in English. Generate a formal legal argument brief section for an immigration case. Structure: Issue Presented, Legal Standard (cite the statute), Statement of Facts, Argument (applying law to facts), Conclusion. Use formal legal citation style.",
    steps: [
      {
        title: "Case",
        fields: ["case_name", "issue_presented"],
      },
      {
        title: "Legal Basis",
        fields: ["applicable_statute", "legal_standard"],
      },
      {
        title: "Argument",
        fields: ["facts", "argument"],
      },
      {
        title: "Conclusion",
        fields: ["conclusion", "attorney_name"],
      },
    ],
  },
  {
    id: "11",
    name: "Evidence Summary",
    slug: "evidence-summary",
    description:
      "Professional evidence summary and exhibit index for immigration filings",
    icon: "ClipboardList",
    category: "Inmigración",
    outputType: "Resumen",
    variables: [
      {
        name: "case_name",
        label: "Case Name",
        type: "text",
        required: true,
        placeholder: "E.g. Matter of Rodriguez, File No. A-123456789",
      },
      {
        name: "applicant_name",
        label: "Applicant Full Name",
        type: "text",
        required: true,
        placeholder: "Full legal name of the applicant",
      },
      {
        name: "submission_date",
        label: "Submission Date",
        type: "date",
        required: true,
      },
      {
        name: "exhibit_list",
        label: "Exhibit List",
        type: "textarea",
        required: true,
        placeholder: "List each exhibit — label, document name, brief description. One per line.\nE.g.\nExhibit A — Passport copy — Identity document\nExhibit B — Employment letter — Establishes qualifying employment",
      },
      {
        name: "relevance_statement",
        label: "Overall Relevance Statement",
        type: "textarea",
        required: true,
        placeholder: "Explain how the body of evidence supports the petition as a whole...",
      },
      {
        name: "attorney_name",
        label: "Attorney Name",
        type: "text",
        required: true,
        placeholder: "Full name of the filing attorney",
      },
    ],
    system_prompt:
      "You are an expert US immigration attorney. Generate the document in English. Generate a professional evidence summary / exhibit index for an immigration filing. List each piece of evidence with its exhibit label, document description, and relevance to the petition. Format as a structured table or numbered list.",
    steps: [
      {
        title: "Case Info",
        fields: ["case_name", "applicant_name", "submission_date"],
      },
      {
        title: "Evidence",
        fields: ["exhibit_list"],
      },
      {
        title: "Finalize",
        fields: ["relevance_statement", "attorney_name"],
      },
    ],
  },
  {
    id: "12",
    name: "Case Summary",
    slug: "case-summary",
    description:
      "Concise internal case summary memo for immigration matters",
    icon: "FolderOpen",
    category: "Inmigración",
    outputType: "Memo",
    variables: [
      {
        name: "client_name",
        label: "Client Full Name",
        type: "text",
        required: true,
        placeholder: "Full legal name of the client",
      },
      {
        name: "a_number",
        label: "A-Number",
        type: "text",
        required: false,
        placeholder: "E.g. A-123 456 789",
      },
      {
        name: "visa_type",
        label: "Visa / Case Type",
        type: "text",
        required: true,
        placeholder: "E.g. H-1B, Marriage-Based Green Card, Asylum",
      },
      {
        name: "case_stage",
        label: "Current Case Stage",
        type: "text",
        required: true,
        placeholder: "E.g. Petition filed, RFE received, Interview scheduled",
      },
      {
        name: "priority_date",
        label: "Priority Date",
        type: "text",
        required: false,
        placeholder: "E.g. January 1, 2022 (leave blank if N/A)",
      },
      {
        name: "filing_date",
        label: "Filing Date",
        type: "date",
        required: false,
      },
      {
        name: "key_dates",
        label: "Key Dates / Deadlines",
        type: "textarea",
        required: true,
        placeholder: "List important dates and deadlines, one per line...",
      },
      {
        name: "current_status",
        label: "Current Status",
        type: "textarea",
        required: true,
        placeholder: "Describe the current status of the case in detail...",
      },
      {
        name: "next_steps",
        label: "Recommended Next Steps",
        type: "textarea",
        required: true,
        placeholder: "List the recommended next actions and who is responsible...",
      },
      {
        name: "assigned_attorney",
        label: "Assigned Attorney",
        type: "text",
        required: true,
        placeholder: "Name of the attorney handling this case",
      },
    ],
    system_prompt:
      "You are an expert US immigration attorney. Generate the document in English. Generate a concise professional case summary memo for an immigration matter. Include client identification, case type, current status, key dates, and recommended next steps. This is an internal firm document.",
    steps: [
      {
        title: "Client",
        fields: ["client_name", "a_number", "visa_type"],
      },
      {
        title: "Case Status",
        fields: ["case_stage", "priority_date", "filing_date"],
      },
      {
        title: "Key Info",
        fields: ["key_dates", "current_status"],
      },
      {
        title: "Next Steps",
        fields: ["next_steps", "assigned_attorney"],
      },
    ],
  },
];

const translationTemplates: Template[] = [
  {
    id: "14",
    name: "Certified Translation (Spanish → English)",
    slug: "certified-translation",
    description:
      "Translate affidavits, declarations, and USCIS documents from Spanish to English and receive a complete package: English translation + original + USCIS-compliant certificate of translation",
    icon: "Languages",
    category: "Immigration — Translation",
    outputType: "Translation Package",
    endpoint: "/api/translate",
    system_prompt: "",
    variables: [
      {
        name: "document_type",
        label: "Document Type",
        type: "select",
        required: true,
        options: [
          "Affidavit / Sworn Statement",
          "Personal Declaration",
          "Support Letter / Carta de Apoyo",
          "Birth Certificate / Acta de Nacimiento",
          "Marriage Certificate / Acta de Matrimonio",
          "Divorce Decree / Decreto de Divorcio",
          "Death Certificate / Acta de Defunción",
          "Police Records / Antecedentes Penales",
          "Court Document / Documento Judicial",
          "Power of Attorney / Poder Notarial",
          "Medical Records / Expediente Médico",
          "Other / Otro",
        ],
      },
      {
        name: "spanish_variant",
        label: "Spanish Dialect / Region of Origin",
        type: "select",
        required: true,
        options: [
          "Mexican Spanish",
          "Colombian Spanish",
          "Central American Spanish (Guatemala, Honduras, El Salvador, Nicaragua)",
          "South American Spanish (Peru, Bolivia, Ecuador)",
          "Southern Cone Spanish (Argentina, Chile, Uruguay)",
          "Caribbean Spanish (Dominican Republic, Cuba, Puerto Rico)",
          "General / Standard Spanish",
        ],
      },
      {
        name: "subject_name",
        label: "Full Name of Document Subject",
        type: "text",
        required: true,
        placeholder: "e.g. María Elena García Pérez",
      },
      {
        name: "original_text",
        label: "Original Spanish Text",
        type: "textarea",
        required: true,
        placeholder: "Paste the full Spanish text here...",
      },
      {
        name: "translator_name",
        label: "Translator / Certifier Name",
        type: "text",
        required: true,
        placeholder: "e.g. Aaron G. Christensen",
      },
      {
        name: "translator_qualifications",
        label: "Translator Qualifications",
        type: "text",
        required: true,
        placeholder: "e.g. Certified paralegal fluent in Spanish and English with 10+ years immigration experience",
      },
    ],
    steps: [
      {
        title: "Document Details",
        fields: ["document_type", "spanish_variant", "subject_name"],
      },
      {
        title: "Original Text",
        fields: ["original_text"],
      },
      {
        title: "Translator Information",
        fields: ["translator_name", "translator_qualifications"],
      },
    ],
  },
];

export const templates: Template[] = [...baseTemplates, ...immigrationTemplates, ...translationTemplates];

export function getTemplateBySlug(slug: string): Template | undefined {
  return templates.find((t) => t.slug === slug);
}
